<html>
<!-- Mirrored from www.pasteur.fr/formation/infobio/python/ch12s03.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 18 Sep 2014 13:38:32 GMT -->
<head>
      <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
   <title>12.3. Raising exceptions</title><meta name="generator" content="DocBook XSL Stylesheets V1.50.0"><meta name="keywords" content="python, biology, bioinformatics, programming, computational biology"><link rel="home" href="index-2.html" title="Introduction to Programming using Python"><link rel="up" href="ch12.html" title="Chapter 12. Exceptions"><link rel="previous" href="ch12s02.html" title="12.2. Python built-in exceptions"><link rel="next" href="ch12s04.html" title="12.4. Defining exceptions"></head><body bgcolor="white" text="black" link="#0000FF" vlink="#840084" alink="#0000FF"><div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">12.3. Raising exceptions</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="ch12s02.html"><img src="images/prev.png" alt="Prev"></a>&nbsp;</td><th width="60%" align="center">Chapter 12. Exceptions</th><td width="20%" align="right">&nbsp;<a accesskey="n" href="ch12s04.html"><img src="images/next.png" alt="Next"></a></td></tr></table><hr></div><div class="sect1"><div class="titlepage"><div><h2 class="title" style="clear: both"><a name="d0e4976"></a>12.3. Raising exceptions</h2></div></div><p>
	You can also <span class="emphasis"><em>raise</em></span> an exception in your
	code, if you consider that the program should be interrupted:
	
	<pre class="programlisting">
	  if something_wrong:
             raise Exception
	</pre>
	You can associate a message to the <tt>raise</tt>
	statement:

	<pre class="programlisting">
	  if something_wrong:
             raise Exception, " something went wrong"
	</pre>

	</p><div class="example"><a name="sa_exc_raise"></a><p class="title"><b>Example 12.3. Raising an exception in case of a wrong DNA character</b></p><p>
	    <pre class="programlisting">
def check_dna(dna, alphabet='atgc'):
    """ using exceptions """
    
    for base in dna:
        if base not in alphabet:
            raise ValueError, "%s not in %s" % (base, alphabet)

    return True
	    </pre>
	  </p></div><p>

      </p></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="ch12s02.html"><img src="images/prev.png" alt="Prev"></a>&nbsp;</td><td width="20%" align="center"><a accesskey="u" href="ch12.html"><img src="images/up.png" alt="Up"></a></td><td width="40%" align="right">&nbsp;<a accesskey="n" href="ch12s04.html"><img src="images/next.png" alt="Next"></a></td></tr><tr><td width="40%" align="left" valign="top">12.2. Python built-in exceptions&nbsp;</td><td width="20%" align="center"><a accesskey="h" href="index-2.html"><img src="images/home.png" alt="Home"></a></td><td width="40%" align="right" valign="top">&nbsp;12.4. Defining exceptions</td></tr></table></div></body>
<!-- Mirrored from www.pasteur.fr/formation/infobio/python/ch12s03.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 18 Sep 2014 13:38:32 GMT -->
</html>