<html>
<!-- Mirrored from www.pasteur.fr/formation/infobio/python/ch12s02.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 18 Sep 2014 13:38:31 GMT -->
<head>
      <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
   <title>12.2. Python built-in exceptions</title><meta name="generator" content="DocBook XSL Stylesheets V1.50.0"><meta name="keywords" content="python, biology, bioinformatics, programming, computational biology"><link rel="home" href="index-2.html" title="Introduction to Programming using Python"><link rel="up" href="ch12.html" title="Chapter 12. Exceptions"><link rel="previous" href="ch12.html" title="Chapter 12. Exceptions"><link rel="next" href="ch12s03.html" title="12.3. Raising exceptions"></head><body bgcolor="white" text="black" link="#0000FF" vlink="#840084" alink="#0000FF"><div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">12.2. Python built-in exceptions</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="ch12.html"><img src="images/prev.png" alt="Prev"></a>&nbsp;</td><th width="60%" align="center">Chapter 12. Exceptions</th><td width="20%" align="right">&nbsp;<a accesskey="n" href="ch12s03.html"><img src="images/next.png" alt="Next"></a></td></tr></table><hr></div><div class="sect1"><div class="titlepage"><div><h2 class="title" style="clear: both"><a name="d0e4930"></a>12.2. Python built-in exceptions</h2></div></div><p>

	Python predefines several exceptions (<a href="ch12s02.html#f_exception_class" title="Figure 12.1. Exceptions class hierarchy">Figure 12.1</a>).

	  </p><div class="figure"><a name="f_exception_class"></a><p class="title"><b>Figure 12.1. Exceptions class hierarchy</b></p><div class="mediaobject"><img src="images/exceptions.png"></div></div><p>    

	</p><div class="itemizedlist"><ul type="disc"><li><tt>AttributeError</tt>: when you attempt to
	    access a non-existing attribute (method or variable) of
	    an object.
	  </li><li><tt>NameError</tt>: failure to find a global
	    name (module, ...)
	  </li><li><tt>IndexError</tt>,
	    <tt>KeyError</tt>: 
	    occurs when attempting to access
	    either an out-of-range index in a list or a non-existing key in a
	    dictionary 
	  </li><li><tt>TypeError</tt>: passing an inappropiate
	    value to an operation
	  </li><li><tt>TabError</tt>,
	    <tt>IndentationError</tt>: two kinds of <tt>SyntaxError</tt></li></ul></div><p>

      </p></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="ch12.html"><img src="images/prev.png" alt="Prev"></a>&nbsp;</td><td width="20%" align="center"><a accesskey="u" href="ch12.html"><img src="images/up.png" alt="Up"></a></td><td width="40%" align="right">&nbsp;<a accesskey="n" href="ch12s03.html"><img src="images/next.png" alt="Next"></a></td></tr><tr><td width="40%" align="left" valign="top">Chapter 12. Exceptions&nbsp;</td><td width="20%" align="center"><a accesskey="h" href="index-2.html"><img src="images/home.png" alt="Home"></a></td><td width="40%" align="right" valign="top">&nbsp;12.3. Raising exceptions</td></tr></table></div></body>
<!-- Mirrored from www.pasteur.fr/formation/infobio/python/ch12s02.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 18 Sep 2014 13:38:32 GMT -->
</html>